parameters:
    species1:
        type:
            electron:
            active: False
        Te:
            val: 0.33
            active: True
            lb: 0.05
            ub: 1.2
        ne:
            val: 0.15
            active: false
            lb: 0.01
            ub: 0.75
        m:
            val: 2.0
            active: false
            lb: 2.0
            ub: 5.0
            matte: False
            intens: 2.0
        fe:
            val: [ ]
            active: False
            length: 3999
            type:
                DLM:
            lb: -100.
            ub: -0.5
            fe_decrease_strict: False
            symmetric: False
            dim: 1
            v_res: 0.05
            temp_asym: 1.0
            m_theta: 0.0
            m_asym: 1.

    species2:
        type:
            ion:
            active: False
        Ti:
            val: 0.1
            active: true
            same: False
            lb: 0.01
            ub: 1.0
        Z:
            val: 16.0
            active: true
            lb: 1.0
            ub: 18.0
        A:
            val: 40.0
            active: False
        fract:
            val: 1.0
            active: False

    general:
        type:
            general:
            active: False
        amp1:
            val: 1.0
            active: false
            lb: 0.01
            ub: 3.75
        amp2:
            val: 1.0
            active: false
            lb: 0.01
            ub: 3.75
        amp3:
            val: 1.0
            active: true
            lb: 0.01
            ub: 3.75
        lam:
            val: 526.4
            active: false
            lb: 526.0
            ub: 527.0
        Te_gradient:
            val: 0.0
            active: false
            lb: 0.
            ub: 10.
            num_grad_points: 1
        ne_gradient:
            val: 0.
            active: False
            lb: 0.
            ub: 15.
            num_grad_points: 1
        ud:
            val: 0.0
            angle: 0.0
            active: true
            lb: -10.0
            ub: 10.0
        Va:
            val: 0.0
            angle: 0.0
            active: true
            lb: -10.0
            ub: 10.0

data:
    shotnum: 102583
    fit_rng:
        blue_min: 465
        blue_max: 515
        red_min: 545
        red_max: 595
        iaw_min: 526.0
        iaw_max: 526.81
        iaw_cf_min: 526.3
        iaw_cf_max: 526.5
    lineouts:
        type:
            pixel
        start: 525
        end: 750
        skip: 75
    background:
        type:
            fit
        slice: 900

other:
    extraoptions:
        spectype: true        
        load_ion_spec: true
        load_ele_spec: true
        fit_IAW: true
        fit_EPWb: true
        fit_EPWr: false

    PhysParams:
        widIRF:
            spect_stddev_ion: 0.015
            spect_stddev_ele: 0.1
            spect_FWHM_ele: 0.9
            ang_FWHM_ele: 1.0
    refit: False
    refit_thresh: 5.0
    calc_sigmas: False


mlflow:
    experiment: inverse-thomson-scattering
    run: IAW example 101675
    #ti 0.15 ud -0.5, amp3 1.6, end 645, va 0 skip 40