data:
  background:
    slice: 310
    type: fit
  fit_rng:
    blue_max: 505
    blue_min: 455
    iaw_cf_max: 526.8
    iaw_cf_min: 526.4
    iaw_max: 527.3
    iaw_min: 526.1
    red_max: 620
    red_min: 550
  lineouts:
    end: 600
    skip: 50
    start: -800
    type: um
  shotnum: 111422
mlflow:
  experiment: julie-inverse-thomson-scattering
  run: IAW 102727 330-710 te gradient = 5
other:
  PhysParams:
    widIRF:
      ang_FWHM_ele: 1.0
      spect_FWHM_ele: 0.9
      spect_stddev_ele: 0.1
      spect_stddev_ion: 0.015
  calc_sigmas: false
  extraoptions:
    fit_EPWb: false
    fit_EPWr: false
    fit_IAW: false
    load_ele_spec: true
    load_ion_spec: true
  refit: false
  refit_thresh: 500
parameters:
  general:
    Te_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 100.0
      val: 0.0
    Va:
      active: false
      angle: 0.0
      lb: -10
      ub: 11.5
      val: 0.0
    amp1:
      active: false
      lb: 0.01
      ub: 3.75
      val: 0.8
    amp2:
      active: false
      lb: 0.01
      ub: 0.45
      val: 0.56
    amp3:
      active: false
      lb: 0.0
      ub: 1.5
      val: 0.1
    lam:
      active: false
      lb: 525.5
      ub: 527.0
      val: 526.5
    ne_gradient:
      active: false
      lb: 0.0
      num_grad_points: 1
      ub: 15.0
      val: 0.0
    type:
      active: false
      general: null
    ud:
      active: false
      angle: 0.0
      lb: -20.0
      ub: 20.0
      val: 0.0
  species1:
    Te:
      active: false
      lb: 0.2
      ub: 1.2
      val: 0.25
    fe:
      active: false
      dim: 1
      fe_decrease_strict: false
      lb: -100.0
      length: 3999
      m_asym: 1.0
      m_theta: 0.0
      symmetric: false
      temp_asym: 1.0
      type:
        DLM: null
      ub: -0.5
      v_res: 0.05
      val: []
    m:
      active: false
      intens: 2.0
      lb: 2.0
      matte: false
      ub: 5.0
      val: 2.0
    ne:
      active: false
      lb: 0.2
      ub: 0.6
      val: 0.04
    type:
      active: false
      electron: null
  species2:
    A:
      active: false
      val: 1.0
    Ti:
      active: false
      lb: 0.0
      same: false
      ub: 1.2
      val: 0.03
    Z:
      active: false
      lb: 0.0
      ub: 1.0
      val: 1.0
    fract:
      active: false
      val: 1.0
    type:
      active: false
      data: null
      ion: null